#!/bin/bash
#
#
#Automated data files exported in test cases.
TEST_CASE_DB_FILE="data/hns_test_case.table"
#
OUTPUT_TEST_DB_FILE="data/report.csv"
#
TEST_CASE_FUNCTION_SWITCH=""
#
TEST_CASE_FUNCTION_NAME=""
#
MESSAGE=""

# Test case mapping table
declare -A case_map
case_map=(
["iperf_ge_port"]="on"
["iperf_xge_port"]="off"
)

#Initial server IP
declare -A initial_ip
initial_ip=(
["192.168.1.181"]="192.168.1.228"
["192.168.1.228"]="192.168.1.181"
["192.168.3.229"]="192.168.3.237"
["192.168.3.237"]="192.168.3.229"
)


#Number of threads
thread=(1 5 10)

#iperf run time
time=20

# Common tools directory path
COMMON_TOOL_PATH="common_tool"

# Test case code directory path
TEST_CASE_PATH="xge_autotest/case_script"
