#!/bin/bash
#
#
#Automated data files exported in test cases.
TEST_CASE_DB_FILE="data/hns_test_case.table"
#
OUTPUT_TEST_DB_FILE="data/report.csv"
#
TEST_CASE_FUNCTION_SWITCH=""
#
TEST_CASE_FUNCTION_NAME=""
#
MESSAGE=""

# Test case mapping table
declare -A case_map
case_map=(
["iperf_ge_port"]="on"
["iperf_xge_port"]="off"
)

#Initial server IP
declare -A initial_ip
initial_ip=(
["192.168.3.238"]="192.168.3.211"
["192.168.3.211"]="192.168.3.238"
["192.168.3.212"]="192.168.3.197"
["192.168.3.192"]="192.168.3.229"
)


#Number of threads
thread=(1 5 10)

#iperf run time
time=20

# Common tools directory path
COMMON_TOOL_PATH="common_tool"

# Test case code directory path
TEST_CASE_PATH="xge_autotest/case_script"

#ifconfig net export IP
local_tp1_ip="192.168.1.10"
local_fibre1_ip="192.168.11.110"
local_fibre2_ip="192.168.12.210"
local_tp1_ipv6_ip="fe80::0db8:0:f101:1/64"
local_fibre1_ipv6_ip="fe80::0db8:0:f101:2/64"

remote_tp1_ip="192.168.1.20"
remote_fibre1_ip="192.168.11.210"
remote_fibre2_ip="192.168.12.220"
