#!/bin/bash

# Test case mapping table
#on - open test case, on - close test case, Default is on.
declare -A case_map=(
#  1 -32b non-prefetchable memory address space support 
["32b_nonprefetchable_memory_address_space_support"]="on"
#  2 -Linux Acpi support
["linux_acpi_support"]="on"
#  3 -PCIe 3.0 equalization support (Hi161x)
["pcie_3.0_equalization_support"]="on"
#  4 -32b prefetchable memory address space support
["32b_prefetchable_memory_address_space_support"]="on"
#  5 -MSI support
["msi_support"]="on"
#  6 -ping function by intel82599 network card
["ping_intel82599_support"]="on"
#  7 -64b prefetchable memory address space support
["64b_prefetchable_memory_address_space_support"]="on"
#  8 -MSI-x support
["msix_support"]="on"
#  9 -Automatic Payload size (Hi161x)
["automatic_payload_size_support"]="on"
#  10 -PCIe 1.0 and 2.0 backward compatibility (Hi161x)
["pcie_1.0_2.0_backward_compatibility"]="on"
)

# Common tools directory path
COMMON_TOOL_PATH="common_tool"

# Test case code directory path
TEST_CASE_PATH="pcie_autotest/case_script"

BACK_IP=192.168.1.248
