#!/bin/bash
#
## Utility function
#


#  call the implementation of the automation use cases
#  IN : N/A
#  OUT: N/A
function test_case_function_run()
{
    if [ x"${TEST_CASE_FUNCTION_SWITCH}" == x"on" ]
    then
        ${TEST_CASE_FUNCTION_NAME}

	if [ x"${MESSAGE}" == x"Pass" ];then
		lava_report "${TEST_CASE_TITLE}" pass
	else
		lava_report "${TEST_CASE_TITLE}" fail
	fi
    else
        MESSAGE="BLOCK\tno automated use cases were implemented."
    fi
}

# Output log file header
# IN : N/A
# OUT: N/A
function writeLogHeader
{
    echo -e "JIRA ID\tDesigned Requirement ID\tTest Case ID\tTest Item\tTest Case Title\tAutomated scripts\tRealize the function\tSwitch\tResult\tReason" > ${OUTPUT_TEST_DB_FILE}
    return 0
}
