#!/bin/bash
#
#
#Automated data files exported in test cases.
TEST_CASE_DB_FILE="data/roce_test_case.table"
#
OUTPUT_TEST_DB_FILE="data/report.csv"
#
TEST_CASE_FUNCTION_SWITCH=""
#
TEST_CASE_FUNCTION_NAME=""
#
MESSAGE=""

#ip_map
#key: the ip of current server eth0
#value: the ip of server eth0 which connects with current server directly
declare -A ip_map
ip_map=(
["192.168.1.210"]="192.168.1.250"
["192.168.1.250"]="192.168.1.210"
["192.168.3.229"]="192.168.3.237"
["192.168.3.237"]="192.168.3.229"
)

declare -A eth_map
eth_map=(
["eth0"]="eth0"
["eth1"]="eth1"
["eth2"]="eth2"
["eth3"]="eth3"
)

# code case index
START_INDEX=0
END_INDEX=3


# Common tools directory path
COMMON_TOOL_PATH="common_tool"

# Test case tool directory path
CASEPATH="roce-test"

