#!/bin/bash
#

#get the eth0's ip in server and client
#IN	: NA
#OUT: NA
function Init_Net_Ip()
{
	#get the ip of server
	LOCAL_IP=`ifconfig eth0 | grep 'inet addr:' | awk '{print $2}' | awk -F':' '{print $2}'`
	echo "The server's ip is ${LOCAL_IP}"

	#get the ip of slave board
	for tmpip in "${!ip_map[@]}"
	do
		if [ "$tmpip"x = "$LOCAL_IP"x ];then
			BACK_IP=${ip_map[$tmpip]}
			break
		fi
	done
	echo "The slave ip is ${BACK_IP}"
}

# Establish a relationship of mutual trust between two boards
# IN : $1 The IP of eth0 in the board as client.
# OUT: N/A
function TrustRelation()
{
	which expect
	[ $? != 0 ] && apt-get install -y expect 1>/dev/null
	rm -f ~/.ssh/*
	ssh-keygen -t rsa -N "" -f ~/.ssh/id_rsa
	#/usr/bin/expect << -EOF			#嵌套expect
	expect -c '
		set timeout -1
		set eth0ip '$1'
		spawn ssh-copy-id root@${eth0ip}
		expect {
			"(yes/no)" { send "yes\r";exp_continue }
			"*password:" { send "root\r"}
			}
		expect -re ":.*#"
		'
	#EOF						#嵌套结束
	return 0
}

function copy_tool_so()
{
	if [ ! -d /lib64 ]
	then
		ln -s /lib /lib64
	fi

	ssh root@${BACK_IP} " if [ ! -d /lib64 ]; then ln -s /lib /lib64; fi;\
						  if [ ! -d ${CASEPATH} ]; then mkdir ${CASEPATH}; fi "
	wait

	pushd ${ROCE_CASE_DIR}

	pushd so
	cp -a * /lib/

	rsync -l * root@${BACK_IP}:/lib/
	popd

	scp roce-test client-auto-5-2 root@${BACK_IP}:${CASEPATH}/

	pushd test
	scp * root@${BACK_IP}:${CASEPATH}/
	popd


	pushd perftest
	scp * root@${BACK_IP}:${CASEPATH}/
	popd

	popd

#config for the roce's kernel driver
	if [ ! -d /usr/local/etc/libibverbs.d ]
	then
		mkdir -p /usr/local/etc/libibverbs.d
		echo "driver hns" > /usr/local/etc/libibverbs.d/hns.driver
	fi

    ssh root@${BACK_IP} " if [ ! -d /usr/local/etc/libibverbs.d ]; \
	then \
		mkdir -p /usr/local/etc/libibverbs.d; \
		echo "driver hns" > /usr/local/etc/libibverbs.d/hns.driver; \
	fi; "
    wait

	return 0

}
#  call the implementation of the automation use cases
#  IN : N/A
#  OUT: N/A
function test_case_function_run()
{
	if [ x"${TEST_CASE_FUNCTION_SWITCH}" == x"on" ]
	then
		${TEST_CASE_FUNCTION_NAME}
	else
		MESSAGE="BLOCK\tno automated use cases were implemented."
	fi
}

# Output log file header
# IN : N/A
# OUT: N/A
function writeLogHeader
{
	echo -e "Designed Requirement ID\tTest Case ID\tTest Item\tTest Case Title\tAutomated scripts\tRealize the function\tSwitch\tResult\tReason" > ${ROCE_TOP_DIR}/${OUTPUT_TEST_DB_FILE}
	return 0
}
