#!/bin/bash
#
#


#
INFO=`cat /etc/hostname`
if [ x"${INFO}" = x"estuary" ]
then
    DEVMEM="devmem"
else
    DEVMEM="devmem2"
fi

#  Test case mapping table
#  on - oepn test case, off - close test case, Default is on.
declare -A case_map=(
#  1 - The driver must support SSP / The driver must support SMP.
["driver_must_support"]="on"
#  2 - Disk negotiated link rate query.
["physical_data_rate"]="on"
#  3 - File transfer stability test.
["stable_2GB_file_transfer"]="on"
#  4 - No cable unplug OOPs
["no_cable_unplug_oops"]="on"
#  5 - Phy control through sysfs.
#  "Be careful:This test case is used only in the environment where the board is connected directly to the disk."
["phy_control_through_sysfs"]="off"
#  6 - support all available sas cores in the Soc.
["support_available_sas_cores"]="on"
#  7 - support full sas function on all available phys.
["support_full_sas_function_all_available_phys"]="off"
#  8 - Support SAS Narrow and Wide Ports.
["narrow_and_wide_ports"]="off"
#  9 - support hotplug
["support_hotplug"]="off"
# 10 - support SMART
["get_sata_SMART_info"]="on"
# 11 - support sata NCQ
["sata_ncq_query"]="on"
# 12 - support Max devices
["support_max_devices"]="on"
# 13 - RAS support
["ras_support"]="on"
)

#  The PHY number of the controller
EFFECTIVE_PHY_NUM=11

#  log file
ERROR_INFO="error_info.log"

#  fio tools configuration file
FIO_CONFG="fio.conf"

#  Common tools directory path
COMMON_TOOL_PATH="common_tool"

#  Test case code directory path
TEST_CASE_PATH="sas_autotest/case_script"

#  phy path
PHY_FILE_PATH="/sys/class/sas_phy"

#  Save all disk partition names
declare -a ALL_DISK_PART_NAME

# FIO tools IO size
FIO_BS=("4M" "4K" "512B")

# FIO tools IO Read and write mode
FIO_RW=("randread" "randwrite" "read" "write" "rw,readwrite" "randrw")

# FIO tools mixed read and write ratio.
IO_RATIO=("10" "50" "90")

# FIO tool parameter list
FIO_PARAMETER_LIST="
[global]
rw=read
direct=1
ramp_time=1
ioengine=psync
iodepth=64
numjobs=1
bs=4M
;zero_buffers=1
group_reporting=1
;ioscheduler=noop
;gtod_reduce=1
;iodepth_batch=2
;iodepth_batch_complete=2
runtime=300
;thread
loops=10
"

#phy address
PHY_ADDR_VALUE=(
"0xa2002000" "0xa2002400"
"0xa2002800" "0xa2002c00"
"0xa2003000" "0xa2003400"
"0xa2003800" "0xa2003c00"
)


### Test case parameter configuration.
## 2 - physical_data_rate
#  negotiated link rate value, Multiple please use the symbol "|" split, Default Value is '1.5|3|6|12', Unit: Gbit.
DISK_NEGOTIATED_LINKRATE_VALUE='1.5|3|6|12'

## 3 - stable_2GB_file_transfer
#  Disk file data consistency test, File comparison times, Default Value is 500.
COMPARISON_NUMBER=500

## 4 - No cable unplug OOPs
#  Long time read / write disk, Default Value is 0.
IS_LONG_TIME_IO_READ_WRITE=0
#  Long time read and write disk time, Default Value is 14400ms.
FIO_LONG_RUN_TIME=14400
#  Repeat read / write disk, Default Value is 0.
IS_REPEAT_IO_READ_WRITE=0
#  Repeat read and write disks. Default value is 100 second.
REPEAT_RW_NUMBER=100
#  FIO tool to read the cycle time.
REPEAT_RM_TIME=10

## 5 - phy_control_through_sysfs
#  loop Rate set up function switch,  1 - oepn test, 0 - close test, Default Value is 0.
IS_LOOP_RATE_SET_UP=0
#  loop Rate set up number, Default Value is 10000.
LOOP_RATE_SET_UP_NUMBER=10000
#  Maximum disk phy, Default Value is "6.0 Gbit".
MAXIMUM_LINK_VALUE="6.0 Gbit"
#  Minimum disk phy, Default Value is "3.0 Gbit".
MINIMUM_LINK_VALUE="3.0 Gbit"

## 6 - support_available_sas_cores
#
BSRANGE="4k-4M"
#
BSSPLIT="4k/30:8k/40:16k/30"

## 7 - support full sas function on all available phys
#  Turn off phy loop count, Default value is 10.
LOOP_PHY_COUNT=10
#
LOOP_PHY_TIME=300

## 8 - Support SAS Narrow and Wide Ports.
#
FIO_RESET_TIME=300
#  Reset the number of Hart_rest or link_reset
RESET_COUNT=5

## 9 - support hotplug
#
FIO_ENABLE_TIME=300

## 12 - support Max devices
#
MAX_DEV_NUM=12

## 13 - RAS support
#
1BIT_ECC_REG_VALUE=(
"0x1" "0x2" "0x4" "0x8" "0x10" "0x20" "0x40" "0x80"
"0x100" "0x200" "0x400" "0x800" "0x1000" "0x2000" "0x4000" "0x8000"
"0x10000" "0x20000" "0x40000" "0x80000"
"0x100000" "0x200000" "0x400000" "0x800000"
)
#
2BIT_ECC_REG_VALUE=(
"0x2" "0x8" "0x20" "0x80" "0x200" "0x800" "0x2000" "0x8000" "0x20000"
)
# Value of SAS_ECCERR_MASK0 register address
MASK_REG_ADDR_VALUE="0xa20001F0"
# Value of CFG_ECCERR_INJECT0_EN register address
INJECT_REG_ADDR_VALUE="0xa2000200"
#
CNT_REG_ADDR_VALUE="0xa2006014"
#
TRSHDC_REG_ADDR_VALUE="0xa2006018"
#
BIT_ECC_TIME=30
#
ECC_INFO_KEY_QUERIES="hgc_dqe_acc1b_intr"
