#!/bin/bash
#



## Utility function
#


#  call the implementation of the automation use cases
#  IN : N/A
#  OUT: N/A
function test_case_function_run()
{
    if [ x"${TEST_CASE_FUNCTION_SWITCH}" == x"on" ]
    then
        #echo "Begin to run testcase: "${TEST_CASE_TITLE}
        ${TEST_CASE_FUNCTION_NAME}
        echo "Message is "${MESSAGE}
        if [ x"${MESSAGE}" = x"PASS" ]
        then
            echo "The result of testcase "${TEST_CASE_TITLE}" is success"
            lava_report "${TEST_CASE_TITLE}" pass
        else
            echo "The result of testcase "${TEST_CASE_TITLE}" is fail"
            lava_report "${TEST_CASE_TITLE}" fail
        fi
    else
        MESSAGE="BLOCK\tno automated use cases were implemented."
        echo "Skip the Scirpt: "${exec_script}
    fi
}

# Output log file header
# IN : N/A
# OUT: N/A
function writeLogHeader
{
    echo -e "Designed Requirement ID\tTest Case ID\tTest Item\tTest Case Title\tAutomated scripts\tRealize the function\tSwitch\tResult\tReason" > ${SAS_TOP_DIR}/${OUTPUT_TEST_DB_FILE}
    return 0
}

#  Judge the current environment, directly connected environment or expander environment.
#  IN : N/A
#  OUT: N/A
function judgment_network_env()
{
    SYS_TYPE=`cat /etc/hostname`
    info=`${DEVMEM} ${CURR_ENV_REG_ADDR} w`
    if [ x"${SYS_TYPE}" = x"ubuntu" ]
    then
        value=`echo ${info} | sed -n '$p' | awk -F ' ' '{print $NF}'`
        [ x"${value}" == x"0x0" ] && return 0
    else
        [ x"${info}" == x"0x00000000" ] && return 0
    fi
    return 1
}

#  Get system disk partition information.
#  IN : N/A
#  OUT: N/A
function get_all_disk_part()
{
    local assert=""

    mout_info=`mount | grep "/dev/[a-z]d[a-z][1-9]" | awk -F ' ' '{print $1}'`
    dev_info=`fdisk -l | grep -o "/dev/[a-z]d[a-z][1-9]"`

    for name in ${dev_info}
    do
        assert=`echo ${mout_info} | grep ${name}`
        if [ x"${assert}" == x"" ] && [ x"name" != x"/dev/sda1" ]
        then
            ALL_DISK_PART_NAME[${#ALL_DISK_PART_NAME[*]}]=$name
            echo "Select disk: "${name}
        fi
        assert=""
    done
}

#  Mount the disk partition to the local.
#  IN : $1 partition disk name
#  OUT: N/A
function mount_disk()
{
    disk_name=$1
    mount_info=`mount | grep -w "^${disk_name}"`
    [ x"${mount_info}" != x"" ] && umount ${disk_name}

    echo "y" | mkfs.ext4 ${disk_name} 1>/dev/null
    mount -t ext4 ${disk_name} /mnt 1>/dev/null
    [ $? -ne 0 ] && return 1

    mount_info=`mount | grep -w "^${disk_name}"`
    [ "${info}" = x"" ] && return 1
    return 0
}

# Configure the FIO tool configuration file.
# IN : N/A
# OUT: N/A
function fio_config()
{
    echo "$FIO_PARAMETER_LIST" > ${FIO_CONFG}
    for dev in "${ALL_DISK_PART_NAME[@]}"
    do
        echo "[job1]" >> ${FIO_CONFG}
        echo "filename=$dev" >> ${FIO_CONFG}
    done
}

# FIO read and write disk
# IN : N/A
# OUT: N/A
function IO_read_write()
{
    for bs in "${FIO_BS[@]}"
    do
        sed -i "{s/^bs=.*/bs=${bs}/g;}" fio.conf
        for rw in "${FIO_RW[@]}"
        do
            sed -i "{s/^rw=.*/rw=${rw}/g;}" fio.conf
            ${SAS_TOP_DIR}/../${COMMON_TOOL_PATH}/fio fio.conf
            if [ $? -ne 0 ]
            then
                MESSAGE="FAIL\tFIO tool in \"${bs}\" disk operation, error."
                return 1
            fi
        done
    done
    return 0
}

# Open and close operation on PHY port.
# IN : $1 - Open or close phy.
#      $2 - PHY port location.
# OUT: N/A
function phy_ops()
{
    case "$1" in
        "close")
            case "$2" in
                [0-7])
                    ${DEVMEM} ${PHY_ADDR_VALUE[$2]} w 0x6
                    ;;
                "all")
                    for phy in  ${PHY_ADDR_VALUE[@]}
                    do
                        ${DEVMEM} ${phy} w 0x6
                    done
                    ;;
            esac
        ;;
        "open")
            case "$2" in
                [0-7])
                ${DEVMEM} ${PHY_ADDR_VALUE[$2]} w 0x7
                ;;
            "all")
                for phy in  ${PHY_ADDR_VALUE[@]}
                do
                    ${DEVMEM} ${phy} w 0x7
                done
                ;;
            esac
        ;;
    esac
}

# Reset file status.
# IN : $1 - Reset file value.
#      $2 - reset file.
# OUT: N/A
function change_sas_phy_file()
{
    dir_info=`ls ${PHY_FILE_PATH}`
    mout_info=`mount | grep "/dev/[a-z]d[a-z][1-9]" | awk -F ' ' '{print $1}'`
    deive_letter_path="device/port/end_device-*/target0*/0:0*/block"

    for dir in ${dir_info}
    do
        str=`cat ${PHY_FILE_PATH}/${dir}/device_type`
        num=`echo "${dir}" | awk -F ":" '{print $NF}'`

        if [ x"${str}" == x"end device" ] && [ ${num} -le ${EFFECTIVE_PHY_NUM} ]
        then
            if [ -d ${PHY_FILE_PATH}/${dir}/${deive_letter_path} ]
            then
                drive_letter=`ls ${PHY_FILE_PATH}/${dir}/${deive_letter_path}`
                info=`echo ${mout_info} | grep ${drive_letter}`
                [ x"${info}" != x"" ] && continue
            fi
            echo $1 > ${PHY_FILE_PATH}/${dir}/$2
            sleep 2
        fi
    done
}

